#!/bin/bash -l
#$ -P llamagrp
#$ -N cache_representation_llama31-405B_moveContent
####$ -l gpus=1
####$ -l gpu_c=6.0
#####$ -l gpu_type=V100
#####$ -l gpu_memory=47G
#$ -l h_rt=12:00:00
#$ -o log
#$ -j y
###$ -m ea
#$ -M zilutang@bu.edu
#$ -t 1

module load cuda/11.8   # 11.2
module load torch/2.1  # using installed 2.2.1 instead
module load miniconda/23.11.0
conda activate /projectnb/mcnet/peter/entity-tracking-gemma/eap_env
export TRANSFORMERS_CACHE=/projectnb2/llamagrp/peter/huggingface_cache/
export HF_DATASETS_CACHE=/projectnb2/llamagrp/peter/huggingface_cache/
export WANDB_PROJECT=entity-tracking-probing
export ROOT=/projectnb/mcnet/peter/entity-tracking-probing
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
index=$(($SGE_TASK_ID-1))

ROOT=/projectnb/mcnet/peter/entity-tracking-probing

python cache_ndif_representations.py \
    --model_type llama \
    --model_name meta-llama/Meta-Llama-3.1-405B \
    --dataset_path $ROOT/data/boxes-dataset-v1/few_shot_boxes_nso_exp2_max3_move_contents \
    --object_vocabulary_file $ROOT/data/objects_with_bnc_frequency.csv \
    --binary \
    --exclude_empty \
    --condition_on the \
    --save_model_representation \
    --model_representation_path $ROOT/model_cache/llama3.1-405b/moveContent \
    --hf_token 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 \
    --ndif_apikey 2ea4eecb38e54fd7ba534fb60519c549
